### ISSUE TITLE
Issue with Kindle version

### ISSUE THREAD

**Issue by piriya33** [jimmysong/programmingbitcoin#106]
Pictures aren't loading in the Kindle version. I both purchased the paperback (waiting for shipment) and Kindle version and pictures wouldn't load in the Kindle web app version of the book. (Haven't looked at it on my actual Kindle yet, will do in a bit)

I have it running on jupyter so that's not a problem, just thought I'd let you guys know,

**Comment by jimmysong** [comment]
Hi, the Kindle version has been updated by my publisher. Please try re-downloading and it should work. Please re-open if there are any issues.
