### ISSUE TITLE
Chapter 1 Fermat's Little Theorem in pow method

### ISSUE THREAD

**Issue by smileymi6** [jimmysong/programmingbitcoin#118]
This is the only part of Chapter One I'm not getting. Thanks in advance if anyone can explain it.

```
def __pow__(self, exponent):
    	n = exponent % (self.prime - 1) (1)
        num = pow(self.num, n, self.prime)
        return self.__class__(num, self.prime)
```
Can anyone explain why its % (self.prime - 1) here and not % (self.prime) as usual?

Book says, we can use % to force out of negative, OK that would give us

`n = exponent % self.prime`

Then it says we can reduce large exponents using a**(p-1) %p = 1, and that gets us to

`n = exponent % (self.prime - 1)`

but I'm not following how exactly.

**Comment by chanhosuh** [comment]
Say an exponent looks like `n = a * (p-1) + b`, then

    x**n == x**(a*(p-1) + b) = x**(a*(p-1)) * x**(b)

where I used that exponentiation turns addition into multiplication `(x**(m+n) == (x**m) * (x**n))`.

But we can simplify further because:

     x**(a*(p-1)) == (x**(p-1)) ** a == 1 ** a == 1

using another property of exponentiation `(x**(m*n) == (x**m)**n)`.

Putting it all together:

    x**n == x ** b 

which means we can simplify large exponents `n` by mod'ing by `p-1`.

**Comment by smileymi6** [comment]
OK, still don't see how you get from there to mod'ing by p-1 :-)

**Comment by chanhosuh** [comment]
My previous response shows that if `b == n % (p-1)`, `x**n == x**b`.

**Comment by smileymi6** [comment]
OK, but unless I'm missing something I still don't see how that answers my question. From the book he says because `a**(p-1) = 1` it's possible to use `% p-1` instead of `%p`. I don't see how this is explained by 

if `b == n % (p-1`) then `x**b % (p-1) == x**n % (p-1)`

Thanks anyway :-)

**Comment by chanhosuh** [comment]
Sorry, there was a typo in my last response.  All my calculations where I use `==` without modulo arithmetic are actually `mod p`, so it should be

> b == n % (p-1), x**b % p == x**n % p

**Comment by smileymi6** [comment]
OK, thanks.

**Comment by jimmysong** [comment]
I really need to explain this better. Thanks for the help @chanhosuh !
