### ISSUE TITLE
mainnet.programmingbitcoin.com appears to be down

### ISSUE THREAD

**Issue by Engelberg** [jimmysong/programmingbitcoin#120]
I've tried a bunch of real-world transaction ids in the mainnet.programmingbitcoin.com site, like

```
http://mainnet.programmingbitcoin.com/tx/e9a66845e05d5abc0ad04ec80f774a7e585c6e8db975962d069a522137b80c1d.hex
```

and not getting any results.

**Comment by jimmysong** [comment]
Sorry, ran out of disk space! Fixed now!
