### ISSUE TITLE
Typo in preface.asciidoc

### ISSUE THREAD

**Issue by HamishMacEwan** [jimmysong/programmingbitcoin#122]
`Warning | This element indicates a waning or caution.`

should be 

`Warning | This element indicates a warning or caution.`

Thanks for the book Jimmy.  I found the "Setting Up" section is a little bit sparse in detail, but it's manageable...

**Comment by jimmysong** [comment]
Thanks for the correction, I'll try to make the setting up section more detailed in the next edition.
