### ISSUE TITLE
Use # to denote comments.  

### ISSUE THREAD

**Issue by miteymouse** [jimmysong/programmingbitcoin#13]
Noticed that you used (1) etc..to correspond to your comments.  Maybe use # instead?

**Comment by leechristie** [comment]
Agree, came here to say that.

**Comment by leechristie** [comment]
> I think those numbers should be at the left of the code like line numnbers in an editor.

Python has no syntax for inline comments. Putting them at the left would comment out the line.

**Comment by educob** [comment]
I am lost  here.
I mean in the book. Not the real python code.

**Comment by leechristie** [comment]
> I am lost here.
> I mean in the book. Not the real python code.

The reason I (and I'm guessing OP too) suggest denoting them with `#` is that the blocks of code in the book with `(1)` etc. on the end of the line don't make it clear to the reader that they're not supposed to type that if they type in the code. If you replace `(1)` with `#(1)` then it won't matter if the reader types those in.

**Comment by jimmysong** [comment]
That's how you do callouts in asciidoc. Unfortunately, there really isn't any other way to comment longer inline.
