### ISSUE TITLE
Correction to finite field defs/examples

### ISSUE THREAD

**Issue by Micah-L** [jimmysong/programmingbitcoin#15]
1. The definition of finite field should start with a _nonempty_ set, to ensure that it contains 0. To be precise, there are also distribution laws, as well as commutativity and associativity of the two operations.

2.
It's a fact, though not immediately obvious, that every finite field contains a prime power number of elements. Thus there is no finite field of order 981 = 3^2 * 109. (in integers modulo 981, the numbers 3, 109, and their multiples don't have multiplicative inverses).

The finite field of order 8 is not what you think it is. If you take the set of integers modulo 8, then 2, 4, and 6 do not have inverses so it will not be a field.

(Notice a pattern? In the integers modulo n, the number m has an inverse if and only if gcd(m,n) = 1. Proof: Euclidean algorithm).

The finite fields of exactly prime order (finite prime fields) are indeed what you think they are.

To get powers, you need to start with the prime field and add on some algebraic elements:
For example, to get the finite field of order 4, you start with F_2 = {0,1} and throw in for example a root of the polynomial x^2+x+1 (note that F_2 does not already contain a root). Call that root a. Then F_4 is {0,1,a,a+1}. This is somewhat analogous to how we construct the complex numbers from the reals by adding a root of x^2+1, this time with finite fields. Note that a+1 is also another root of x^2+x+1. Addition works by treating 1 and a as linearly independent elements and multiplication works by remembering that a^2 + a + 1 =0 i.e. a^2 = a+1. (Since -1 = 1).
To get F_8, you need to add on some more algebraic elements coming from polynomial roots. The polynomial x^4+x+1 will do the trick. If a root of it is b, then F_8 becomes {0,1,a,a+1,b,b+1,a+b,a+b+1}. You can check that this really does satisfy the definition of a field. For example the mult inverse of a is a+1 since a(a+1) = a^2 + a = a+1 + a = 2a+1 = 0a + 1 = 1.

Maybe you want to focus on finite prime fields (according to standard math terminology, the rational numbers is a "prime field" (the only non finite one), so there is a need to say "finite prime field" here). To make this more accessible, you could ignore the thing I said about prime powers and just mention that the integers modulo n is a field exactly when n is a prime (the proof of this should be accessible), but finite fields of prime power order exist and are not really used here. When n is not prime, inverses of non-zero elements wont always exist (and this looser structure is often called a ring).

**Comment by jimmysong** [comment]
I tried to explain in chapter 1 a bit better:

Notice the order of the field is always 1 more than the largest element.
You might have noticed that the field has a prime order every time.
For a variety of reasons that will become clear later, it turns out that fields _must_ have an order that is a power of a prime, but that the Finite Fields whose order is prime are the ones we're interested in.

Please log another issue if I got something wrong.
