### ISSUE TITLE
Image in Ch. 3 is incorrect

### ISSUE THREAD

**Issue by huetsch** [jimmysong/programmingbitcoin#19]
https://github.com/jimmysong/programmingbitcoin/blob/master/ch03.asciidoc#elliptic-curves-over-finite-fields

I believe the image listed under the title "Elliptic Curves over Finite Fields" is actually still displaying the "Elliptic Curves over Reals" image. It should be a different image and is confusing to the reader.

**Comment by jimmysong** [comment]
Yes, this has been fixed.
