### ISSUE TITLE
Ch. 1 Spelling/Grammatical Corrections

### ISSUE THREAD

**Issue by Jason-Les** [jimmysong/programmingbitcoin#20]
### Pg. 13

> Think of Finite Fields as something that you could have learned in High School
instead of _Trigonomotry_, just that the education system you’re a part of decided that
_Trigonomotry_ was more important for you to learn. 

_Trigonometry_ misspelled 

> ...Elliptic Curve Cryptography. That, _in turn_ is essential for… 

Should be a comma following _in turn_

### Pg. 14

> Let’s unpack each of the _following_.

Should be “above” instead of “following” (since its referencing the list above) and maybe followed by a colon

> We name the elements 0, 1, 2, _etc_ because they’re convenient for our purposes.

_etc_ should have a period at the end, "etc."

### Pg 15.

> If not, we _got_ an invalid Field Element

Change _got_ to "have" or maybe "get"

### Pg. 18

> _After all_ 11+~f~17=9 just doesn’t look right for most people because they’re not used to Finite Field addition.

Add a comma proceeding _After all_. Fix the finite field addition symbol.

### Pg. 21

> The difference here is that the exponent is not a field element, _so_ has to be treated a bit differently

Insert "it" after _so_

### Pg. 25

> We want, _for example_ something like this to work:

Insert comma after _for example_

### Pg. 26

In _thes_ chapter we learned about Finite Fields and how to implement it in Python. We’ll be utilizing _thes_ in Chapter 3 for Elliptic Curve Cryptography.

"This" mispelled as _thes_ in two instances

**Comment by plazma48** [comment]
yea i put a pull request for page 26 typo of "thes" to "this" in two instance.....

**Comment by plazma48** [comment]
nice....:-)

**Comment by smh69** [comment]
Ch1, ipynb, ex5: I suspect the exercise should be in F19 and not F97
Ch1, ipynb, ex8 : 'F 31' reads with funny subscript because '31' needs enclosing curly braces.
ecc.py: generic messages when TypeError raised might be better as 'Cannot operate on two...' rather than 'Cannot add two...' if exact operation is not part of the message.

**Comment by jimmysong** [comment]
These are all fixed, thank you!
