### ISSUE TITLE
Chapter 9, Exercise 9 Error 

### ISSUE THREAD

**Issue by vvronskyFX** [jimmysong/programmingbitcoin#251]
Getting this output error when running the solution to Exercise 9 in Chapter 9:
![image](https://user-images.githubusercontent.com/64465297/185278321-6b8cb777-dab2-4bab-abc7-01cd8a3804a7.png)

Here's the code that's running the test:
![image](https://user-images.githubusercontent.com/64465297/185278826-51fada03-5ad9-4865-8d46-50991012fecb.png)

I've commented out the difficulty portion in this block as pointed out by @bolatovumar here: https://github.com/jimmysong/programmingbitcoin/issues/179

Here's my code for `bits_to_target` in helper.py:
![image](https://user-images.githubusercontent.com/64465297/185279084-03a2e035-5baa-4898-8802-375227412d47.png)

Not sure why I'm getting this. Has anyone went through this portion experience this? Cheers for the help!

**Comment by bolatovumar** [comment]
You are getting a `NotImplementedError` which means there is some code that's missing that needs to be filled in.

**Comment by vvronskyFX** [comment]
> You are getting a `NotImplementedError` which means there is some code that's missing that needs to be filled in.

That's why I'm posting in here because i can't find what I may be missing. I went through the solutions and wrote in the code for each exercise. 

Getting the same error. It has something to do with this `bits_to_target` and anything involving `target` somehow.

**Comment by vvronskyFX** [comment]
![image](https://user-images.githubusercontent.com/64465297/185296478-5081b3b7-77cd-452d-93bd-29d746d53164.png)

Error still appearing in Ex. 10, Ex. 11, Ex. 12. Been scanning around the files trying to see but I haven't found any block of code that has `NotImplementedError` anywhere. It almost seems like a bug but I'm not sure.

**Comment by vvronskyFX** [comment]
> 

Right after Ex. 11, the example that goes into "difficulty adjustment" outputs this error: 
![Screen Shot 2022-08-18 at 9 26 39 AM](https://user-images.githubusercontent.com/64465297/185418858-ff04e955-20dc-43e8-8a8d-5533279bc018.png)

Could it be something in the packages?

**Comment by vvronskyFX** [comment]
FIXED!

**Solution:**
Coding `calculate_new_bits` in Exercise 13. Looks like that was the missing piece. I re-ran the cells again and all tests and exercises passed as they should! 

![image](https://user-images.githubusercontent.com/64465297/185514143-2c21d3b9-302a-4c66-9ef0-05c988f010f2.png)

Thanks for your support earlier @bolatovumar. I will be closing this issue.
