### ISSUE TITLE
Can not visit the link https://faucet.programmingbitcoin.com

### ISSUE THREAD

**Issue by U-F-O** [jimmysong/programmingbitcoin#278]
Hi, I try to finish the questions in chapter 4 Exercise 9. It suggest visit the link https://faucet.programmingbitcoin.com. but not it fails, @jimmysong  Could you please help?  Is the website off?

**Comment by derekpa** [comment]
I used this one

http://beyondfaucet.com/btc-testnet

**Comment by U-F-O** [comment]
> I used this one
> 
> http://beyondfaucet.com/btc-testnet

Seems currently it is offline. 

Thanks for your attention.

**Comment by derekpa** [comment]
OK, try this one, still seems to be up.

https://kuttler.eu/en/bitcoin/btc/faucet/

**Comment by U-F-O** [comment]
> OK, try this one, still seems to be up.
> 
> https://kuttler.eu/en/bitcoin/btc/faucet/

Thanks.
