### ISSUE TITLE
Ch 01 - Using modulo p-1 to improve __pow__ operator.

### ISSUE THREAD

**Issue by smileymi6** [jimmysong/programmingbitcoin#28]
```
 def __pow__(self, exponent):
    	n = exponent % (self.prime - 1) (1)
        num = pow(self.num, n, self.prime)
        return self.__class__(num, self.prime)
```

> Make the exponent into something within the 0 to p-1 range.

Actually the range here is 0 to p-2 is it not, as its modulo p-1?

Also this is something I couldn't intuitively follow and would prefer a little more elaboration. So far we have only multiplied by n^p-1 to deal with negative exponents and used modulo p to map integers into the field of p and personally I couldn't make the jump to mow applying modulo p-1.

**Comment by jimmysong** [comment]
Thanks! Adding this to the next update.
