### ISSUE TITLE
Chapter 3: Bug in __rmul__

### ISSUE THREAD

**Issue by BrownBurger** [jimmysong/programmingbitcoin#37]
The calculation of the number of bits in \_\_rmul\_\_ is done as follows:
```python
    def __rmul__(self, coefficient):
        bits = math.ceil(math.log(coefficient, 2))
        ...
```
However, this doesn't seem to work if the coefficient is 1, 2, 4, 8, 16...  A simple fix could be:

     bits = coefficient.bit_length()

Btw, the (1) for this code line is also missing.

**Comment by anujanegi** [comment]
I would like to claim this issue!

**Comment by BrownBurger** [comment]
Has been fixed.
