### ISSUE TITLE
Real-Time Community for Contributors

### ISSUE THREAD

**Issue by crodrigues** [jimmysong/programmingbitcoin#4]
@jimmysong Congratulations on the book deal! It would be pretty nice to have a Slack/IRC/Discord/something where would-be contributors could follow your uncommitted progress and discuss the project. Do you happen to have any plans for such an online community?

**Comment by youssefnotes** [comment]
Slack

**Comment by advgamer** [comment]
discord :)

**Comment by jachiang** [comment]
@youssefnotes is the slack invite only?

**Comment by jimmysong** [comment]
Sorry guys, unfortunately, contributing is going to be limited because of some copyright restrictions I've found out about.
