### ISSUE TITLE
Ch.4 derive y from x

### ISSUE THREAD

**Issue by jl2012** [jimmysong/programmingbitcoin#45]
After y is derived from x, you need to verify that (x,y) is a valid point of the curve

https://github.com/bitcoin-core/secp256k1/blob/master/src/field_impl.h#L130

**Comment by smh69** [comment]
after derivation of y via x and the curve params, as long as it's done correctly, is it not true that the point must necessarily be on the curve? or am i missing edge cases?

**Comment by jl2012** [comment]
If and only if x is a valid x

**Comment by jimmysong** [comment]
Oh, good point. Thanks for bringing it to my attention!

**Comment by jimmysong** [comment]
Turns out that the `Point` class will test to see if (x,y) is on the curve so this is not a problem.
