### ISSUE TITLE
Ch 5 version 2 txs

### ISSUE THREAD

**Issue by jl2012** [jimmysong/programmingbitcoin#48]
> transactions utilizing an OP code called OP_CHECKSEQUENCEVERIFY as defined in BIP0068

OP_CHECKSEQUENCEVERIFY is BIP112, which depends on BIP68. However, both BIP112 and BIP68 use version 2.

**Comment by jl2012** [comment]
> Sequence was originally intended as a way to do payment channels (see sidebar), but is currently used with Replace-By-Fee and **Check Sequence Verify.**

Better call it relative lock-time, as in BIP68

**Comment by jimmysong** [comment]
thanks! both were fixed in editing.
