### ISSUE TITLE
Ch 9 BIP9

### ISSUE THREAD

**Issue by jl2012** [jimmysong/programmingbitcoin#53]
> The only soft forks to utilize BIP9 have been BIP141 (segwit) and BIP91 (reducing threshold for segwit). 

The CSV softfork (BIP68,112,113) was the first one activated by BIP9, using bit 0

BIP91 did not follow the BIP9 default parameters (80% over less than 3 days), and essentially no one except mining pools run BIP91. Maybe you could mention it as a sidenote, but this is not a good example of a normal softfork

**Comment by jimmysong** [comment]
This has been added.
