### ISSUE TITLE
chapter 4 thoughts

### ISSUE THREAD

**Issue by smh69** [jimmysong/programmingbitcoin#57]
In helper.py: At first glance, I think of a base58 value more as an array of chr ie: a string, than I think of it as an array of bytes. therefore:
  perhaps BASE58_ALPHABET is more clearly expressed as a normal string and not bytes?
  Similary, in encode_base58():
    prefix is encoding the leading zeros, so I see it more like BASE58_ALPHABET[0] * count
    and result could just as easily be initialized as the empty string '',
    and built like `result = base58_ALPHABET[mod] + result`
    and returned like `return prefix + result`
  Related, encode_base58_checksum() would no longer need to `.decode('ascii')` and decode_base58() would not need to `.encode('ascii')`, but... big but, what else would break? I have no clue yet.
  More related: asciidoc changes would also be needed as encode_base58() and encode_base58_checksum() are discussed in chapter 4.

I know this is rather nit-picky, what really caught my eye was the expression `prefix = b'1' * count` which made think about 0x31 instead of hinting me straight towards index-0 of the base58 alphabet, then I realized that base58 results are all being treated like bytes instead of strings while in helper.py.

**Comment by jimmysong** [comment]
excellent suggestion! Thankfully, I have unit tests all written, so this isn't nearly as hard to make work. Coming in in the next set of commits.
