### ISSUE TITLE
chapter 5 spelling/typos

### ISSUE THREAD

**Issue by smh69** [jimmysong/programmingbitcoin#58]
While explaining 'version':
  * the first paragraph has the phrase "...that's a version number that's very differnt than Windows 8 or Windows 10." where "different" is missing the second "e".
  * the last paragraph has a sentence "It actually is when the interpreted as a little-endian integer..." which has an un-needed "the".

Just after the 'varint/compact_size' sidebar, the phrase "Each input contains 4 fields, the first two which point ot the previous transaction..." has "ot" where "to" was intended.

In the paragraph following the bullet list of tx_in fields, the sentence "Thus, we need to define exactly which output within a transactio that we’re spending." spells "transaction" in bold without the last "n".

~~In the last exercise which tests Tx.fee(), you've implemented TxIn.fetch_tx() which relies on a TxIn.cache
attribute which was never setup in TxIn.__init__().  if `self.cache = {}` is not setup in __init__(), maybe at least a hint "fetch_tx() was added after we started coding TxIn, feel free to initialize any required attributes that it needs." would be helpful.~~ (appears fixed with break-out of TxFetcher class in commit 30a5007601b5ed5d8850a13bcce060dbfa787231)

**Comment by jimmysong** [comment]
fixed.
