### ISSUE TITLE
chapter 7, thoughts

### ISSUE THREAD

**Issue by smh69** [jimmysong/programmingbitcoin#63]
By far, this chapter wiped me out.  Here are my thoughts/experiences/troubles.

The writing was rather good, or Im not seeing typos/spelling mistakes because Im tired.

I kicked myself, having to struggle through the 2nd exercise Tx.verify_input() because Id written Tx.sig_hash() to indeed use a tx copy, but not deep.  Specifically, sig_hash() tests passed and z was properly calculated, but Id blown away my real tx inputs so verify_input() couldnt possibly succeed.  Perhaps unit-tests that check if the tx has changed from how it was originally created fromhex could fail during the sig_hash() tests and lead the coder to fix this likely common mistake.  I dont recall enough of a warning in the written text but I already had this in the back of my mind as I started with sig_hash()... I just didnt go deep enough and was using the original TxIn instances.

I think I altered Tx.fee() which had an optional testnet boolean param however since the Tx is always initialized for mainnet or testnet, I didnt feel I should have to remember what Im doing when calculating a fee, rather it should just be passing self.testnet into TxIn.value().

I also started Tx.sig_hash() by setting script_sig values to b'\x00' however I needed to set these to Script([]) instead (at least when more than one input) because script_sig later needs to implement .serialize() which Script() does but bytes() does not.

When working on the last exercise, I found myself wanting a from_wif() function but couldnt find where that was implemented... so I cheated instead, but at the time I thought it would be handy.

I got lucky enough to find faucets that all spent from segwit utxos... I suspect the transaction parser was choking on these with the 2b offset between version and inputs, but I was getting strange error messages as if Script was running into unknown opcodes (212 in my case, read marker as no-inputs, the flag as 1 output, first 8b of my input prev-txid as the first tx amount, and then failed in Script.parse() somewhere in the middle of that first input's prev-txid)... so I think the cursor was out of place.  I ended up sending regular tx's to the addresses created earlier and didnt have the same problem once I was spending from utxos that had no witness.  I could see many others possibly having similar problems, unless there are specific faucets to select txs that will not have have witness fields.  One thought might be for TxFetcher to know if segwit is supported and be able to pass this in the request to http://tbtc.programmingblockchain.com:18332/rest/tx/non-segwit/ and for that url to return old-style serialization... until the library supports segwit parsing.

I realized that Jimmy is hard at work, I think since the last chapter, as I couldnt match-up my local git copy with what I was reading online.  I think Im working on a moving target, so I will take a break and see how far Jimmy gets.   Im really enjoying this work, I suspect that Programming Bitcoin will be one of the 'must have' references for coders.  Go Jimmy!

**Comment by jimmysong** [comment]
Yes, I redid the entire sig_hash not requiring a deep copy of the tx but instead doing it step-by-step. This is the approach I used in Chapter 13 for segwit as well. Hope that helps you! Exercises should be simpler.
