### ISSUE TITLE
Modulo math with negative numbers

### ISSUE THREAD

**Issue by jachiang** [jimmysong/programmingbitcoin#7]
Hi @jimmysong 
 I propose extending the clock model for negative numbers, for both the dividend and divisor:

For negative dividend, it is like turning the clock counterclockwise, as you have described:
`-4 % 12 = 8`
![negDividendImg](https://ipfs.io/ipfs/QmbLQzt52mrz4VW8jAicBL7A8wkm9Lch3x8XCZ9CghRA3a)

For negative divisor, it is like the clock hours are negative, and ordered counterclockwise:
`-4 % -12 = -4`
![negDivisorImg](https://ipfs.io/ipfs/QmZtvMi6MJxbHLQEk8s4NUmYTnygmEMwdNuG4Q4oQxgptH)

Cheerio!

**Comment by jimmysong** [comment]
Doing it for the divisor could be interesting, but it's not really necessary to understand Finite Fields. Would be an interesting math to think about, though!
