### ISSUE TITLE
Chapter 9: check_pow()

### ISSUE THREAD

**Issue by BrownBurger** [jimmysong/programmingbitcoin#73]
The check_pow() method uses hash256() to get the hash:
```python

    def check_pow(self):
        '''Returns whether this block satisfies proof of work'''
        sha = hash256(self.serialize())
        proof = little_endian_to_int(sha)
        return proof < self.target()
```
I wonder if there is a particular reason why the hash() method that was created in a previous exercise isn't used here instead.

**Comment by jimmysong** [comment]
Because we have `little_endian_to_int` written already. We'd have to use something ugly like `int.from_bytes(self.hash(), 'big')` . This is a little cleaner.
