### ISSUE TITLE
Chapter 11: Variable name in parse()

### ISSUE THREAD

**Issue by BrownBurger** [jimmysong/programmingbitcoin#80]
in the [Solution for Exercise 6](https://github.com/jimmysong/programmingbitcoin/blob/master/appa.asciidoc#exercise-6-6) the variable that contains the number of hashes is called „num_txs“:
```python
class MerkleBlock:
...
    def parse(cls, s):
        ...
        num_txs = read_varint(s)
        hashes = []
        for _ in range(num_txs):
            hashes.append(s.read(32)[::-1])
        ...
```
Something like „num_hashes“ would make more sense..

**Comment by jimmysong** [comment]
I agree. Made the change.
