### ISSUE TITLE
Just a question about "There are as many possible private keys in Bitcoin as there are atoms in a billion galaxies"

### ISSUE THREAD

**Issue by educob** [jimmysong/programmingbitcoin#88]
I have read the same comment in Andreas Antonoupolus book and I think the bitcoin security implications are not really right.

The public key is hashed into 160 bits. So I think that means that many private keys end up producing the same bitcoin address many times (2^256 / 2^160 = 7.9x10^²28 times). 

So the security of bitcoins in a bitcoin address is not 10^77 but aprox 10^29.

Am I wrong?

Thanks for your book.

**Comment by jimmysong** [comment]
The wording was chosen purposefully for that reason, but yes, you're right it's much less. The math is a little off, though. To find a single p2pkh address, it would be 2^160, or ~10^48, which is still huge.
