### ISSUE TITLE
Chapter 6. web:  http://wiki.bitcoin.it doesn't seem to work.

### ISSUE THREAD

**Issue by educob** [jimmysong/programmingbitcoin#90]
Hi.

I found the wiki in [https://en.bitcoin.it/wiki/Main_Page](url)

In particular de list of opcodes is in [https://en.bitcoin.it/wiki/Script](url)

**Comment by jimmysong** [comment]
Yep, changed.

**Comment by justinmoon** [comment]
This same dead link is in chapter 10, too

**Comment by jimmysong** [comment]
yep fixed.
