### ISSUE TITLE
Chapter 13: Different transaction indexes

### ISSUE THREAD

**Issue by BrownBurger** [jimmysong/programmingbitcoin#92]
On [Figure 1](https://github.com/jimmysong/programmingbitcoin/blob/master/images/p2wpkh1.png) the transaction index in the example transaction is 01000000. But in the field description it is 00000000

![grafik](https://user-images.githubusercontent.com/43646864/49238524-decdb280-f400-11e8-9907-2aa1f008d001.png)

**Comment by jimmysong** [comment]
fixed, thanks!
