### ISSUE TITLE
Chapter 13: Field descriptions in Figure 20

### ISSUE THREAD

**Issue by BrownBurger** [jimmysong/programmingbitcoin#93]
The part that describes the fields of the transaction in [Figure 20](https://raw.githubusercontent.com/jimmysong/programmingbitcoin/master/images/p2wsh-3.png) contains several items that are not in that transaction. It's actually the same description as that of [Figure 21](https://raw.githubusercontent.com/jimmysong/programmingbitcoin/master/images/p2wsh-4.png).

![grafik](https://user-images.githubusercontent.com/43646864/49239238-7bdd1b00-f402-11e8-9111-46e04dfd2f14.png)

**Comment by educob** [comment]
Also figures 29 p2wsh Step 4 & figure 30 p2wsh Step 5 are the same pic.

ps: I cannot believe I finally understand segwit.

**Comment by jimmysong** [comment]
Thanks Fixed!
