### ISSUE TITLE
Chapter 13: No explanation in the book about fee calculation for segwit scripts.

### ISSUE THREAD

**Issue by educob** [jimmysong/programmingbitcoin#94]
Hi.

If I am correct fee calculation has changed with segwit. 
Weight is used instead of bytes length.
Unfortunately nothing is said about that in the book.
Are fees calculated the same (with weight) for all 4 segwit scripts (p2wpkh, p2sh-p2wpkh, p2wsh, p2sh-p2wsh) or just for the "pure" ones (p2wpkh, p2wsh).

Calculating fees is for me a terrible problem cause they are deciding when you add inputs & outpus but after that comes the signing, adding redeem scripts, etc. 
Fees is something that has to be explained in detail.

**Comment by jimmysong** [comment]
Indeed it has, and no, I didn't add in how to do the weighing. I'll be sure to cover it in the next edition or another book.
