### ISSUE TITLE
Chapter 13: Use of pre/post-prefixes

### ISSUE THREAD

**Issue by BrownBurger** [jimmysong/programmingbitcoin#95]
The chapter uses several times the „pre/post“-prefix for different BIPs. For example:

> Pay-to-witness-script-hash as seen by pre-BIP0141 software

> However, post-Segwit nodes will now have encountered the special Script sequence for p2wsh ...

Technically „pre“ / „post“ refer to the period before/after a specific event. So „post-SegWit nodes“ actually means every node after the activation of SegWit. But not all nodes supported Segwit after its activation. So a better way to phrase it could be „Segwit-aware nodes“ or „Segwit nodes“.

However, I guess that virtually all readers would interpret the „post/pre“-prefixes in the intended way. So this is probably a bit nit-picky...

**Comment by jimmysong** [comment]
Agreed, I'll probably change the wording for the next edition.
